### ISSUE TITLE
PIE support for Android "Lollipop"

### ISSUE THREAD

**Issue by wzyboy** [tatsuhiro-t/spdylay#129]
I used to run `shrpx` on my Android 4.x device and it worked quite well. However, when trying to execute the same file on Android 5.x, I got this error:

    error: only position independent executables (PIE) are supported.

A quick Google search brought me to https://github.com/tatsuhiro-t/aria2/issues/321 . (BTW aria2 is also a great project :-)

It seems like this "PIE" issue exists not only in `aria2` Android version, but also in `shrpx`, and in `nghttpx`, too IMHO.

Could you help updating Android Makefile / Dockerfile / docs to resolve thie "PIE" issue in `shrpx` and `nghttpx`? Thanks for your great work!

**Comment by tatsuhiro-t** [comment]
Since HTTP/2 deprecates SPDY *very soon*, we only invest our time in nghttp2 development for now.

**Comment by wzyboy** [comment]
Should I close this issue and report it to nghttp2 project instead? I have not tested if `nghttpx` for Android supports PIE, but I did not see `PID` in `Dockerfile.android` for `nghttpx`...

**Comment by tatsuhiro-t** [comment]
Added PIE flags in nghttp2's android-config via https://github.com/tatsuhiro-t/nghttp2/commit/6ca24264e4139619c2a9a8407a2e082ceb14a618
I think we can close this issue.

**Comment by wzyboy** [comment]
Great, thanks!

**Comment by tatsuhiro-t** [comment]
Right, updated Dockerfile.android too. Enjoy.
