### ISSUE TITLE
curl -vOa http://*.html from shrpx "shrpx -p -b xxx:80 --backend-spdy-no-tls -L INFO" ,can not show properly

### ISSUE THREAD

**Issue by megarzzy** [tatsuhiro-t/spdylay#138]
1. start sharp by "shrpx -p -b xxx:80 --backend-spdy-no-tls -L INFO"
2. curl -vOa http://*.html  -x 127.0.0.1:3000,     -O can download the html 
3. open the downloaded html by IE or Firfox ,but browser can not read and parse the html,
it seems messy code in the browser

**Comment by tatsuhiro-t** [comment]
shrpx is not actively maintained these days.  We have nghttpx HTTP/2 proxy, which is HTTP/2 replacement of shrpx. https://github.com/tatsuhiro-t/nghttp2
Could you test it with this reproduction steps?
