### ISSUE TITLE
libtool: link: unsupported hardcode properties [ubuntu 12.10]

### ISSUE THREAD

**Issue by ant0ine** [tatsuhiro-t/spdylay#55]
I got the following error during compilation on ubuntu 12.10:

libtool: link: unsupported hardcode properties

which I solved by installing the following package:

g++-mingw-w64-i686

It may help other people to update the README file.

**Comment by tjdett** [comment]
Hit this too. `./configure --enable-static` failed, but `./configure` (where static is enabled by default) succeeded. Very strange.

**Comment by lutoma** [comment]
Had the same issue on Debian 8.2 right now. g++ was missing, but `./configure` still worked. Trying to compile after that using `make` failed, and continued to fail after installing g++. I had to actually `./configure` again after installing g++ for it to compile.
