### ISSUE TITLE
building for andriod - cstring: No such file or directory

### ISSUE THREAD

**Issue by loudest** [tatsuhiro-t/spdylay#83]
I'm trying to build for android and i'm getting the error:

/home/src/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -march=armv7-a -mfloat-abi=softfp --sysroot=/home/src/android-ndk/platforms/android-9/arch-arm/ -DHAVE_CONFIG_H -I. -I..  -Wall -I./../lib/includes -I./../lib/includes -I/home/src/android-ndk/usr/local/include    -I/home/src/android-ndk//usr/local/include   -DHAVE_CONFIG_H -I/home/src/android-ndk//usr/local/include  -g -O2 -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o util.cc
In file included from util.cc:25:0:
util.h:30:19: fatal error: cstring: No such file or directory
 #include <cstring>
                   ^
compilation terminated.

**Comment by sambc-SDK** [comment]
Thanks for your attention, and it works well now.
